server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ex_jpa_security
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  private-key: eaB9NNZx8VRdykh7gsmaZHKeSVWLajfr9kaDmy8ah/Q=